apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
- role: control-plane
  image: kindest/node:v1.24.0
- role: worker
  image: kindest/node:v1.24.0
  extraPortMappings:
  - containerPort: 8080
    hostPort: 8080
    listenAddress: "127.0.0.1"
    protocol: TCP
- role: worker
  image: kindest/node:v1.24.0
- role: worker
  image: kindest/node:v1.24.0
